# Install required roles with
# cd provisioning
# ansible-galaxy install -r requirements.yml -p roles

- src: newrelic.newrelic-infra
  version: 0.3.0

- src: rvm.ruby
  version: v2.0.1

- src: geerlingguy.certbot
  version: 3.0.0

- src: DavidWittman.redis
  version: 1.2.0

- src: ANXS.postgresql
  version: v1.0.3

- src: abtris.nginx-passenger
  version: da82e7312488747b1e06a4af242aa52ffacad60b
